# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]

data_folder: /home2/data/TIMIT
test_clean_folder: !ref <data_folder>/TEST/clean

output_folder: ./results/waveunet/TIMIT
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
enhanced_folder: !ref <output_folder>/enhanced

# Wav2vec version
wav2vec_version: 1.0
wav2vec1_model: ./data/pretrained/wav2vec_large.pt
wav2vec2_model: ./data/pretrained/libri960_big.pt'

# Basic parameters
use_tensorboard: True
tensorboard_logs: !ref <output_folder>/logs/

# Data files
csv_train: !ref <output_folder>/save/train.csv
csv_valid: !ref <output_folder>/save/valid.csv
csv_test: !ref <output_folder>/save/test.csv

hdf5_train: !ref <data_folder>/train.hdf5
hdf5_test: !ref <data_folder>/test.hdf5
hdf5_valid: !ref <data_folder>/valid.hdf5

# Training Parameters
number_of_epochs: 1000
N_batch: 30
lr: 0.001
weight_decay: 0.001
device: 'cuda:0'
Sample_rate: 16000

output_size: 1
model: !new:waveunet.Waveunet
    num_channels: [32, 64, 128, 256, 512, 1024]
    kernel_size: 5
    target_output_size: !ref <output_size> * <Sample_rate>
    conv_type: 'gn'
    res: 'fixed'


train_dataset: !new:data.SeparationDataset
    hdf_file: !ref <hdf5_train>
    sr: !ref <Sample_rate>
    channels: 1
    random_hops: False

valid_dataset: !new:data.EvaluationDataset
    hdf_file: !ref <hdf5_valid>
    sr: !ref <Sample_rate>
    channels: 1

test_dataset: !new:data.EvaluationDataset
    hdf_file: !ref <hdf5_test>
    sr: !ref <Sample_rate>
    channels: 1

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>
    summary_fns:
        loss: !name:speechbrain.utils.train_logger.summarize_average

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

compute_cost: !name:speechbrain.nnet.losses.mse_loss

optimizer: !new:speechbrain.nnet.optimizers.Adam_Optimizer
    learning_rate: !ref <lr>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        optimizer: !ref <optimizer>
        counter: !ref <epoch_counter>
