# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]

dataset: voicebank
data_folder: /home/data/voicebank  #* MAzBio vs. AzBio
test_clean_folder: !ref <data_folder>/TEST/clean

output_folder: ./results/waveunet/voicebank  #* MAzBio vs. AzBio
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
enhanced_folder: !ref <output_folder>/enhanced

pretrained_model: "pase"  # "dfl", "wav2vec", or "pase"

# Wav2vec version
wav2vec_version: 1.0  #* MAzBio vs. AzBio
wav2vec1_model: ./data/pretrained/wav2vec_large.pt
wav2vec2_model: ./data/pretrained/libri960_big.pt
wav2vec_loss_layers: [0, 1]  #* MAzBio vs. AzBio

set_weights_epoch: 1

# dfl:
dfl_model: ./data/pretrained/dfl.pt
dfl_layers: 6

# pase
pase_model: ./data/pretrained/FE_e199.ckpt
pase_cfg: ./data/pretrained/PASE+.cfg

# Basic parameters
use_tensorboard: False
tensorboard_logs: !ref <output_folder>/logs/

# Data files
csv_train: !ref <output_folder>/save/train.csv
csv_valid: !ref <output_folder>/save/valid.csv
csv_test: !ref <output_folder>/save/test.csv

hdf5_train: !ref <data_folder>/train.hdf5
hdf5_test: !ref <data_folder>/test.hdf5
hdf5_valid: !ref <data_folder>/valid.hdf5

# Training Parameters
combined_loss: True
weights_ratio: 1.00:0.01
basic_loss: MSE # MSE, SM, RI, or PCM
number_of_epochs: 150
N_batch: 30 # TIMIT
lr: 0.0001
weight_decay: 0.001
Sample_rate: 16000

# Device
device: 'cuda:0'
device2: 'cuda:1'
use_device2: False

output_size: 1 #* MAzBio vs. AzBio
model: !new:waveunet.Waveunet
    num_levels: 12  # 6 or 12
    features: 24  # 32 or 24
    #num_channels: [32, 64, 128, 256, 512, 1024]
    feature_growth: 'add'  # 'add' or 'double'
    kernel_size: 5
    target_output_size: !ref <output_size> * <Sample_rate>
    conv_type: 'gn'
    res: 'fixed'

train_dataset: !new:data.SeparationDataset
    hdf_file: !ref <hdf5_train>
    sr: !ref <Sample_rate>
    channels: 1
    random_hops: False

train_dataset2: !new:data.FullSeparationDataset
    hdf_file: !ref <hdf5_train>
    sr: !ref <Sample_rate>
    channels: 1

valid_dataset: !new:data.EvaluationDataset
    hdf_file: !ref <hdf5_valid>
    sr: !ref <Sample_rate>
    channels: 1

test_dataset: !new:data.EvaluationDataset
    hdf_file: !ref <hdf5_test>
    sr: !ref <Sample_rate>
    channels: 1

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>
    summary_fns:
        loss: !name:speechbrain.utils.train_logger.summarize_average

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

mse_cost: !name:speechbrain.nnet.losses.mse_loss

optimizer: !new:speechbrain.nnet.optimizers.Adam_Optimizer
    learning_rate: !ref <lr>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        optimizer: !ref <optimizer>
        counter: !ref <epoch_counter>
